apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: blazor-workshop
  namespace: flux-system
spec:
  interval: 1m
  path: ./charts
  prune: true
  sourceRef:
    kind: GitRepository
    name: blazor-workshop
