apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: blazor-workshop
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/your-username/blazor-workshop
  branch: main
