apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blazor-workshop
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: blazor-workshop
      sourceRef:
        kind: HelmRepository
        name: blazor-local
      version: "0.1.0"
  values:
    ingress:
      enabled: true
      host: parsaeian.ponya.ir
    sentry:
      enabled: true
      dsn: "https://your-sentry-dsn"
