apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: blazor-gitops
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/mrparsaeian/blazor-gitops
  ref:
    branch: main
