apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: blazor-workshop
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: blazor-gitops
  path: "./manifests"
  prune: true
  targetNamespace: default
