name: Deploy GitOps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Reconcile Flux
        run: |
          curl -s https://fluxcd.io/install.sh | bash
          flux reconcile source git blazor-workshop
          flux reconcile helmrelease blazor-frontend
          flux reconcile helmrelease blazor-backend
          flux reconcile helmrelease sentry
